---
- name: Pre-reqs setup task
  include: pre-setup.yaml

- name: Install and configure docker
  include: setup_docker.yml
  when: container_runtime == "docker"

- name: Install and configure cri-o container runtime
  include: setup_crio.yml
  when: container_runtime == "cri-o"

- name: Install and configure containerd container runtime
  include: setup_containerd.yml
  when: container_runtime == "containerd"

- name: Install k8s packages
  include: install.yml

- name: Configure firewalld
  include: configure_firewalld.yml
  when: configure_firewalld

- name: Check if Kubernetes has already been initialized.
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubernetes_init_stat

# Initialize Master
- include_tasks: configure_master.yml
  when: "'master' in group_names"

- name: Get the kubeadm join command from the Kubernetes master.
  command: kubeadm token create --print-join-command
  changed_when: false
  when: "'master' in group_names"
  register: kubernetes_join_command_result

- name: Set the kubeadm join command globally.
  set_fact:
    kubernetes_join_command: >
      {{ kubernetes_join_command_result.stdout }}
      {{ kubernetes_join_command_extra_opts }}
  when: kubernetes_join_command_result.stdout is defined
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items: "{{ groups['all'] }}"

# Initialize Nodes
- include_tasks: configure_node.yml
  when: "'master' not in group_names"

# Configure kubernetes
- include_tasks: post-setup.yml
  when: "'master' in group_names"