---
- name: Setup required sysctl params
  sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value }}'
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - {key: net.bridge.bridge-nf-call-ip6tables, value: 1}
    - {key: net.bridge.bridge-nf-call-iptables,  value: 1}
    - {key: net.ipv4.ip_forward,  value: 1}

- name: Add CRI-O repo
  yum_repository:
    name: cri-o
    description: CRI-O repo
    baseurl: https://cbs.centos.org/repos/{{ crio_repo_version }}/$basearch/os/

- name: Install cri-o
  yum:
    name: cri-o
    state: present
    update_cache: yes
    disable_gpg_check: yes

- name: Start and enable crio service
  service:
    name: crio
    state: started
    enabled: yes
    daemon_reload: yes
