---
- name: Add docker repository
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo

- name: Install containerd
  package:
    name: "containerd.io"
    state: present

- name: Create containerd directories required
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/containerd

- name: Configure containerd
  command: containerd config default > /etc/containerd/config.toml

- name: Start and enable containerd service
  systemd:
    name: containerd
    state: restarted
    enabled: yes
    daemon_reload: yes